UPDATE all_tampere_samples ns
SET 
    d_count_1 = CAST(t.d_count_1 AS FLOAT),
    d_count_2 = CAST(t.d_count_2 AS FLOAT),
    d_count_3 = CAST(t.d_count_3 AS FLOAT),
    d_count_4 = CAST(t.d_count_4 AS FLOAT),
    d_count_5 = CAST(t.d_count_5 AS FLOAT),
    d_count_6 = CAST(t.d_count_6 AS FLOAT),
    d_count_7 = CAST(t.d_count_7 AS FLOAT),
    d_count_9 = CAST(t.d_count_9 AS FLOAT),
    d_speed_1 = CAST(t.d_speed_1 AS FLOAT),
    d_speed_2 = CAST(t.d_speed_2 AS FLOAT),
    d_speed_3 = CAST(t.d_speed_3 AS FLOAT),
    d_speed_4 = CAST(t.d_speed_4 AS FLOAT),
    d_speed_5 = CAST(t.d_speed_5 AS FLOAT),
    d_speed_6 = CAST(t.d_speed_6 AS FLOAT),
    d_speed_7 = CAST(t.d_speed_7 AS FLOAT),
    d_speed_9 = CAST(t.d_speed_9 AS FLOAT),
    d_count_light = CAST(t.d_count_light AS FLOAT),
    d_count_heavy = CAST(t.d_count_heavy AS FLOAT),
    d_speed_light = CAST(t.d_speed_light AS FLOAT),
    d_speed_heavy = CAST(t.d_speed_heavy AS FLOAT),
    n_count_1 = CAST(t.n_count_1 AS FLOAT),
    n_count_2 = CAST(t.n_count_2 AS FLOAT),
    n_count_3 = CAST(t.n_count_3 AS FLOAT),
    n_count_4 = CAST(t.n_count_4 AS FLOAT),
    n_count_5 = CAST(t.n_count_5 AS FLOAT),
    n_count_6 = CAST(t.n_count_6 AS FLOAT),
    n_count_7 = CAST(t.n_count_7 AS FLOAT),
    n_count_9 = CAST(t.n_count_9 AS FLOAT),
    n_speed_1 = CAST(t.n_speed_1 AS FLOAT),
    n_speed_2 = CAST(t.n_speed_2 AS FLOAT),
    n_speed_3 = CAST(t.n_speed_3 AS FLOAT),
    n_speed_4 = CAST(t.n_speed_4 AS FLOAT),
    n_speed_5 = CAST(t.n_speed_5 AS FLOAT),
    n_speed_6 = CAST(t.n_speed_6 AS FLOAT),
    n_speed_7 = CAST(t.n_speed_7 AS FLOAT),
    n_speed_9 = CAST(t.n_speed_9 AS FLOAT),
    n_count_light = CAST(t.n_count_light AS FLOAT),
    n_count_heavy = CAST(t.n_count_heavy AS FLOAT),
    n_speed_light = CAST(t.n_speed_light AS FLOAT),
    n_speed_heavy = CAST(t.n_speed_heavy AS FLOAT)
FROM traffic_tampere_year t
WHERE ns.tmsnumber = CAST(t."tmsNumber" AS FLOAT);

-- 1s