-- 1s

UPDATE new_sampled ns
SET 
    d_count_1 = CAST(t.d_count_1 AS FLOAT),
    d_count_2 = CAST(t.d_count_2 AS FLOAT),
    d_count_3 = CAST(t.d_count_3 AS FLOAT),
    d_count_4 = CAST(t.d_count_4 AS FLOAT),
    d_count_5 = CAST(t.d_count_5 AS FLOAT),
    d_count_6 = CAST(t.d_count_6 AS FLOAT),
    d_count_7 = CAST(t.d_count_7 AS FLOAT),
    d_count_9 = CAST(t.d_count_9 AS FLOAT),
    d_speed_1 = CAST(t.d_speed_1 AS FLOAT),
    d_speed_2 = CAST(t.d_speed_2 AS FLOAT),
    d_speed_3 = CAST(t.d_speed_3 AS FLOAT),
    d_speed_4 = CAST(t.d_speed_4 AS FLOAT),
    d_speed_5 = CAST(t.d_speed_5 AS FLOAT),
    d_speed_6 = CAST(t.d_speed_6 AS FLOAT),
    d_speed_7 = CAST(t.d_speed_7 AS FLOAT),
    d_speed_9 = CAST(t.d_speed_9 AS FLOAT),
    d_count_light = CAST(t.d_count_light AS FLOAT),
    d_count_heavy = CAST(t.d_count_heavy AS FLOAT),
    d_speed_light = CAST(t.d_speed_light AS FLOAT),
    d_speed_heavy = CAST(t.d_speed_heavy AS FLOAT),
    n_count_1 = CAST(t.n_count_1 AS FLOAT),
    n_count_2 = CAST(t.n_count_2 AS FLOAT),
    n_count_3 = CAST(t.n_count_3 AS FLOAT),
    n_count_4 = CAST(t.n_count_4 AS FLOAT),
    n_count_5 = CAST(t.n_count_5 AS FLOAT),
    n_count_6 = CAST(t.n_count_6 AS FLOAT),
    n_count_7 = CAST(t.n_count_7 AS FLOAT),
    n_count_9 = CAST(t.n_count_9 AS FLOAT),
    n_speed_1 = CAST(t.n_speed_1 AS FLOAT),
    n_speed_2 = CAST(t.n_speed_2 AS FLOAT),
    n_speed_3 = CAST(t.n_speed_3 AS FLOAT),
    n_speed_4 = CAST(t.n_speed_4 AS FLOAT),
    n_speed_5 = CAST(t.n_speed_5 AS FLOAT),
    n_speed_6 = CAST(t.n_speed_6 AS FLOAT),
    n_speed_7 = CAST(t.n_speed_7 AS FLOAT),
    n_speed_9 = CAST(t.n_speed_9 AS FLOAT),
    n_count_light = CAST(t.n_count_light AS FLOAT),
    n_count_heavy = CAST(t.n_count_heavy AS FLOAT),
    n_speed_light = CAST(t.n_speed_light AS FLOAT),
    n_speed_heavy = CAST(t.n_speed_heavy AS FLOAT)
FROM traffic_tampere_year t
WHERE ns.tmsnumber = CAST(t."tmsNumber" AS FLOAT);

-- old
-- UPDATE new_sampled ns
-- SET 
-- 	"date" = t."date",
--     d_count_1 = t.d_count_1,
--     d_count_2 = t.d_count_2,
--     d_count_3 = t.d_count_3,
--     d_count_4 = t.d_count_4,
--     d_count_5 = t.d_count_5,
--     d_count_6 = t.d_count_6,
--     d_count_7 = t.d_count_7,
--     d_count_9 = t.d_count_9,
--     d_speed_1 = t.d_speed_1,
--     d_speed_2 = t.d_speed_2,
--     d_speed_3 = t.d_speed_3,
--     d_speed_4 = t.d_speed_4,
--     d_speed_5 = t.d_speed_5,
--     d_speed_6 = t.d_speed_6,
--     d_speed_7 = t.d_speed_7,
--     d_speed_9 = t.d_speed_9,
--     d_count_light = t.d_count_light,
--     d_count_heavy = t.d_count_heavy,
--     d_speed_light = t.d_speed_light,
--     d_speed_heavy = t.d_speed_heavy,
--     n_count_1 = t.n_count_1,
--     n_count_2 = t.n_count_2,
--     n_count_3 = t.n_count_3,
--     n_count_4 = t.n_count_4,
--     n_count_5 = t.n_count_5,
--     n_count_6 = t.n_count_6,
--     n_count_7 = t.n_count_7,
--     n_count_9 = t.n_count_9,
--     n_speed_1 = t.n_speed_1,
--     n_speed_2 = t.n_speed_2,
--     n_speed_3 = t.n_speed_3,
--     n_speed_4 = t.n_speed_4,
--     n_speed_5 = t.n_speed_5,
--     n_speed_6 = t.n_speed_6,
--     n_speed_7 = t.n_speed_7,
--     n_speed_9 = t.n_speed_9,
--     n_count_light = t.n_count_light,
--     n_count_heavy = t.n_count_heavy,
--     n_speed_light = t.n_speed_light,
--     n_speed_heavy = t.n_speed_heavy
-- FROM traffic t
-- WHERE ns.tmsnumber = t."tmsNumber";