INSERT INTO new_sampled (
	-- id,
    d_noise_lvl,
    n_noise_lvl,
    geom,
    log_dist_motorway,
    motorway_length_100m,
    motorway_length_200m,
    motorway_length_400m,
    motorway_length_800m,
    motorway_length_1600m,
    log_dist_trunk,
    trunk_length_100m,
    trunk_length_200m,
    trunk_length_400m,
    trunk_length_800m,
    trunk_length_1600m,
    log_dist_primary,
    primary_length_100m,
    primary_length_200m,
    primary_length_400m,
    primary_length_800m,
    primary_length_1600m,
    log_dist_secondary,
    secondary_length_100m,
    secondary_length_200m,
    secondary_length_400m,
    secondary_length_800m,
    secondary_length_1600m,
    log_dist_tertiary,
    tertiary_length_100m,
    tertiary_length_200m,
    tertiary_length_400m,
    tertiary_length_800m,
    tertiary_length_1600m,
    log_dist_residential,
    residential_length_100m,
    residential_length_200m,
    residential_length_400m,
    residential_length_800m,
    residential_length_1600m,
	log_dist_water,
	elevation_dem,
	elevation_tpi_100m,
	elevation_tpi_200m,
	elevation_tpi_400m,
	elevation_tpi_800m,
	elevation_tpi_1600m,
	building_density_100m,
	building_density_200m,
	building_density_400m,
	building_density_800m,
	building_density_1600m,
	building_tpi_100m,
	local_build_height_100m,
	avg_building_height_100m,
	building_tpi_200m,
	local_build_height_200m,
	avg_building_height_200m,
	building_tpi_400m,
	local_build_height_400m,
	avg_building_height_400m,
	building_tpi_800m,
	local_build_height_800m,
	avg_building_height_800m,
	building_tpi_1600m,
	local_build_height_1600m,
	avg_building_height_1600m,
	log_dist_pub,
	sound_blocked,
	log_dist_block,
	crossing_200m,
	traffic_light_200m,
	tmsnumber,
	"date",
    d_count_1,
    d_count_2,
    d_count_3,
    d_count_4,
    d_count_5,
    d_count_6,
    d_count_7,
    d_count_9,
    d_speed_1,
    d_speed_2,
    d_speed_3,
    d_speed_4,
    d_speed_5,
    d_speed_6,
    d_speed_7,
    d_speed_9,
    d_count_light,
    d_count_heavy,
    d_speed_light,
    d_speed_heavy,
    n_count_1,
    n_count_2,
    n_count_3,
    n_count_4,
    n_count_5,
    n_count_6,
    n_count_7,
    n_count_9,
    n_speed_1,
    n_speed_2,
    n_speed_3,
    n_speed_4,
    n_speed_5,
    n_speed_6,
    n_speed_7,
    n_speed_9,
    n_count_light,
    n_count_heavy,
    n_speed_light,
    n_speed_heavy
)
SELECT 
	-- id,
    noise_lvl AS d_noise_lvl,
	n_noise_lvl,
    geom,
    log_dist_motorway,
    motorway_length_100m,
    motorway_length_200m,
    motorway_length_400m,
    motorway_length_800m,
    motorway_length_1600m,
    log_dist_trunk,
    trunk_length_100m,
    trunk_length_200m,
    trunk_length_400m,
    trunk_length_800m,
    trunk_length_1600m,
    log_dist_primary,
    primary_length_100m,
    primary_length_200m,
    primary_length_400m,
    primary_length_800m,
    primary_length_1600m,
    log_dist_secondary,
    secondary_length_100m,
    secondary_length_200m,
    secondary_length_400m,
    secondary_length_800m,
    secondary_length_1600m,
    log_dist_tertiary,
    tertiary_length_100m,
    tertiary_length_200m,
    tertiary_length_400m,
    tertiary_length_800m,
    tertiary_length_1600m,
    log_dist_residential,
    residential_length_100m,
    residential_length_200m,
    residential_length_400m,
    residential_length_800m,
    residential_length_1600m,
    log_dist_water				,
	elevation_dem				,
	elevation_tpi_100m 			,
	elevation_tpi_200m 			,
	elevation_tpi_400m 			,
	elevation_tpi_800m 			,
	elevation_tpi_1600m 		,
	building_density_100m		,
	building_density_200m		,
	building_density_400m		,
	building_density_800m		,
	building_density_1600m		,
	building_tpi_100m 			,
	local_build_height_100m		,
	avg_building_height_100m	,
	building_tpi_200m 			,
	local_build_height_200m		,
	avg_building_height_200m	,
	building_tpi_400m 			,
	local_build_height_400m		,
	avg_building_height_400m	,
	building_tpi_800m 			,
	local_build_height_800m		,
	avg_building_height_800m	,
	building_tpi_1600m 			,
	local_build_height_1600m	,
	avg_building_height_1600m	,
	log_dist_pub,
	sound_blocked,
	log_dist_block,
	crossing_200m,
	traffic_light_200m,
    tmsnumber,
    "date",
    d_count_1,
    d_count_2,
    d_count_3,
    d_count_4,
    d_count_5,
    d_count_6,
    d_count_7,
    d_count_9,
    d_speed_1,
    d_speed_2,
    d_speed_3,
    d_speed_4,
    d_speed_5,
    d_speed_6,
    d_speed_7,
    d_speed_9,
    d_count_light,
    d_count_heavy,
    d_speed_light,
    d_speed_heavy,
    n_count_1,
    n_count_2,
    n_count_3,
    n_count_4,
    n_count_5,
    n_count_6,
    n_count_7,
    n_count_9,
    n_speed_1,
    n_speed_2,
    n_speed_3,
    n_speed_4,
    n_speed_5,
    n_speed_6,
    n_speed_7,
    n_speed_9,
    n_count_light,
    n_count_heavy,
    n_speed_light,
    n_speed_heavy
FROM sampled_points;